### ISSUE TITLE
Game crashes on second (dying) hit on fire

### ISSUE THREAD

**Issue by Mehequanna** [ShamylZakariya/Platformer#1]
I run this on MacOS. It seems when I am to be killed by the fire, the app crashes. I get this error back in the terminal:
`zsh: illegal hardware instruction  cargo run`

**Comment by ShamylZakariya** [comment]
It's been a while! But I've updated to a newer version of `winit` and `wgpu`, the crashing bug might be fixed?

**Comment by Mehequanna** [comment]
Hmm, I'll have to try this out in the near future :)

**Comment by Mehequanna** [comment]
It works! Thanks :)
